export enum FeatureIndex {
	CandleClose = 0,
	CandleVolume = 1,
	CandleReturnRatio = 2,
	CandlePositionRatio = 3,
	CandleRangeRatio = 4,
	CandleOpen = 5,
	CandleHigh = 6,
	CandleLow = 7,
	CandleVolumeRatio = 8,
	OrderBookAvgBid = 9,
	OrderBookAvgAsk = 10,
	OrderBookSpreadRatio = 11,
	OrderBookImbalance = 12,
	BookTickerBid = 13,
	BookTickerAsk = 14,
	BookTickerSpreadRatio = 15,
	TradeAvgPrice = 16,
	TradeTotalQty = 17,
	TradeBuyRatio = 18,
	TickerPriceChange = 19,
	TickerVolume = 20,
	TickerDailyRange = 21,
	PriceSnapshot = 22,
	SlidingWindowStart = 23,
	SlidingWindowEnd = 30,
	Bias = 31,
}
