version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/services/discovery-server'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/services/financial-scraper'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/services/message-manager'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/services/trader-trainer'
    schedule:
      interval: 'weekly'
