export default {
  parserPreset: {
    parserOpts: {
      headerPattern: /^(:\w+:|\p{Emoji})(?:\(([\w$.\-*/ ]+)\))?!?: (.+)$/u,
      headerCorrespondence: ['emoji', 'scope', 'subject'],
    },
  },
  rules: {
    'header-match-emoji-pattern': [2, 'always'],
    'scope-enum': [
      2,
      'always',
      [
        'address-manager',
        'admin-interface',
        'api',
        'api-gateway',
        'audit-logger',
        'auth',
        'broker',
        'certificate-authority',
        'certificate-client',
        'certificate-utils',
        'common',
        'config',
        'core',
        'database',
        'deps',
        'discovery',
        'discovery-server',
        'dlq-service',
        'docs',
        'docker',
        'eslint',
        'examples',
        'financial-scraper',
        'github-actions',
        'husky',
        'k8s',
        'message-manager',
        'middleware',
        'multiple',
        'observability',
        'release',
        'router',
        'scraper',
        'scripts',
        'tests',
        'trader-trainer',
        'trainer',
        'types',
        'utils',
        'wallet',
      ],
    ],
    'scope-case': [2, 'always', 'lowerCase'],
    'subject-empty': [2, 'never'],
    'subject-case': [0],
    'subject-full-stop': [2, 'never', '.'],
    'body-leading-blank': [2, 'always'],
    'footer-leading-blank': [2, 'always'],
  },
  plugins: [
    {
      rules: {
        'header-match-emoji-pattern': ({ header }) => {
          const pattern = /^(:\w+:|\p{Emoji})(?:\(([\w$.\-*/ ]+)\))?!?: (.+)$/u;
          return [
            pattern.test(header),
            `Header must match Gitmoji format: "<gitmoji>(<scope>): <subject>"`,
          ];
        },
      },
    },
  ],
};
