import type { SourceType } from "@trading-model/common/config/event.types";
import type {
	TradingSymbol,
	UnixTimestamp,
} from "@trading-model/common/domain/primitives";
import { Table } from "ts-sql-query/Table";

import { DBConnection } from "../../../config/db";
import type { BookTickerData } from "../market-data.types";

const T_BOOK_TICKER = new (class TBookTicker extends Table<
	DBConnection,
	"TBookTicker"
> {
	id = this.autogeneratedPrimaryKey("id", "int");
	symbol = this.primaryKey("symbol", "string");
	market = this.column("market", "string");
	source = this.column("source", "string");
	bid = this.column("bid", "double");
	ask = this.column("ask", "double");
	bidQty = this.column("bid_qty", "double");
	askQty = this.column("ask_qty", "double");
	timestamp = this.primaryKey("timestamp", "localDateTime");

	constructor() {
		super("market_book_tickers");
	}
})();

const SELECT = {
	symbol: T_BOOK_TICKER.symbol,
	market: T_BOOK_TICKER.market,
	source: T_BOOK_TICKER.source,
	bid: T_BOOK_TICKER.bid,
	ask: T_BOOK_TICKER.ask,
	bidQty: T_BOOK_TICKER.bidQty,
	askQty: T_BOOK_TICKER.askQty,
	timestamp: T_BOOK_TICKER.timestamp,
};

export const insertBookTicker = async (
	data: BookTickerData[]
): Promise<void> => {
	if (!data.length) {
		return;
	}

	await new DBConnection()
		.insertInto(T_BOOK_TICKER)
		.values(
			data.map((item) => ({
				symbol: item.symbol,
				market: item.market,
				source: item.source,
				bid: item.bid,
				ask: item.ask,
				bidQty: item.bidQty,
				askQty: item.askQty,
				timestamp: new Date(item.timestamp),
			}))
		)
		.executeInsert();
};

export const selectBookTickerBy = {
	symbol: async (symbol: TradingSymbol) => {
		return await new DBConnection()
			.selectFrom(T_BOOK_TICKER)
			.where(T_BOOK_TICKER.symbol.equals(symbol))
			.select(SELECT)
			.executeSelectMany();
	},
	timestamp: {
		after: async (timestamp: UnixTimestamp) => {
			return await new DBConnection()
				.selectFrom(T_BOOK_TICKER)
				.where(T_BOOK_TICKER.timestamp.greaterOrEquals(new Date(timestamp)))
				.select(SELECT)
				.executeSelectMany();
		},
		before: async (timestamp: UnixTimestamp) => {
			return await new DBConnection()
				.selectFrom(T_BOOK_TICKER)
				.where(T_BOOK_TICKER.timestamp.lessOrEquals(new Date(timestamp)))
				.select(SELECT)
				.executeSelectMany();
		},
	},
	source: async (source: SourceType) => {
		return await new DBConnection()
			.selectFrom(T_BOOK_TICKER)
			.where(T_BOOK_TICKER.source.equals(source))
			.select(SELECT)
			.executeSelectMany();
	},
};
