import { Table } from 'ts-sql-query/Table';

import { DBConnection } from '../../../config/db';
import { BookTickerData } from '../market-data.types';

const tBookTicker = new (class TBookTicker extends Table<DBConnection, 'TBookTicker'> {
  id = this.autogeneratedPrimaryKey('id', 'int');
  symbol = this.primaryKey('symbol', 'string');
  market = this.column('market', 'string');
  source = this.column('source', 'string');
  bid = this.column('bid', 'double');
  ask = this.column('ask', 'double');
  bidQty = this.column('bid_qty', 'double');
  askQty = this.column('ask_qty', 'double');
  timestamp = this.primaryKey('timestamp', 'localDateTime');

  constructor() {
    super('market_book_tickers');
  }
})();

const select = {
  symbol: tBookTicker.symbol,
  market: tBookTicker.market,
  source: tBookTicker.source,
  bid: tBookTicker.bid,
  ask: tBookTicker.ask,
  bidQty: tBookTicker.bidQty,
  askQty: tBookTicker.askQty,
  timestamp: tBookTicker.timestamp,
};

export const insertBookTicker = async (data: BookTickerData[]): Promise<void> => {
  if (!data.length) return;

  await new DBConnection()
    .insertInto(tBookTicker)
    .values(
      data.map(d => ({
        symbol: d.symbol,
        market: d.market,
        source: d.source,
        bid: d.bid,
        ask: d.ask,
        bidQty: d.bidQty,
        askQty: d.askQty,
        timestamp: new Date(d.timestamp),
      }))
    )
    .executeInsert();
};

export const selectBookTickerBy = {
  symbol: async (symbol: string) => {
    return await new DBConnection()
      .selectFrom(tBookTicker)
      .where(tBookTicker.symbol.equals(symbol))
      .select(select)
      .executeSelectMany();
  },
  timestamp: {
    after: async (timestamp: Date) => {
      return await new DBConnection()
        .selectFrom(tBookTicker)
        .where(tBookTicker.timestamp.greaterOrEquals(timestamp))
        .select(select)
        .executeSelectMany();
    },
    before: async (timestamp: Date) => {
      return await new DBConnection()
        .selectFrom(tBookTicker)
        .where(tBookTicker.timestamp.lessOrEquals(timestamp))
        .select(select)
        .executeSelectMany();
    },
  },
  source: async (source: string) => {
    return await new DBConnection()
      .selectFrom(tBookTicker)
      .where(tBookTicker.source.equals(source))
      .select(select)
      .executeSelectMany();
  },
};

// CREATE TABLE `market_book_tickers` (
//     `id`          INT NOT NULL AUTO_INCREMENT,
//     `symbol`      VARCHAR(32) NOT NULL,
//     `market`      VARCHAR(16) NOT NULL,
//     `source`      VARCHAR(32) NOT NULL,
//     `bid`         DECIMAL(20,10) NOT NULL,
//     `ask`         DECIMAL(20,10) NOT NULL,
//     `bid_qty`     DECIMAL(30,10) NOT NULL,
//     `ask_qty`     DECIMAL(30,10) NOT NULL,
//     `timestamp`   DATETIME(3) NOT NULL,
//
//     PRIMARY KEY (`symbol`, `timestamp`),
//     INDEX `idx_mbt_timestamp` (`timestamp` ASC) INVISIBLE,
//     INDEX `idx_mbt_symbol` (`symbol` ASC) VISIBLE)
// ) ENGINE=InnoDB;
