import { Table } from "ts-sql-query/Table";

import { DBConnection } from "../../../config/db";
import type { CandleData } from "../market-data.types";

const T_MARKET_CANDLES = new (class TMarketCandles extends Table<
	DBConnection,
	"TMarketCandles"
> {
	id = this.autogeneratedPrimaryKey("id", "int");

	symbol = this.primaryKey("symbol", "string");
	market = this.primaryKey("market", "string");
	source = this.primaryKey("source", "string");
	interval = this.primaryKey("interval_value", "string");

	low = this.column("low", "double");
	open = this.column("open", "double");
	high = this.column("high", "double");
	close = this.column("close", "double");
	volume = this.column("volume", "double");
	trades = this.optionalColumn("trades", "int");

	closeTimestamp = this.column("close_timestamp", "localDateTime");
	timestamp = this.primaryKey("timestamp", "localDateTime");

	constructor() {
		super("market_candles");
	}
})();

const SELECT = {
	low: T_MARKET_CANDLES.low,
	open: T_MARKET_CANDLES.open,
	high: T_MARKET_CANDLES.high,
	close: T_MARKET_CANDLES.close,
	symbol: T_MARKET_CANDLES.symbol,
	market: T_MARKET_CANDLES.market,
	source: T_MARKET_CANDLES.source,
	volume: T_MARKET_CANDLES.volume,
	interval: T_MARKET_CANDLES.interval,
	trades: T_MARKET_CANDLES.trades,
	timestamp: T_MARKET_CANDLES.timestamp,
	closeTimestamp: T_MARKET_CANDLES.closeTimestamp,
};

function _toCandleRow(item: CandleData): Record<string, unknown> {
	return {
		low: item.low,
		open: item.open,
		high: item.high,
		close: item.close,
		symbol: item.symbol,
		market: item.market,
		source: item.source,
		volume: item.volume,
		interval: item.interval,
		trades: item.trades ?? null,
		timestamp: new Date(item.timestamp),
		closeTimestamp: new Date(item.closeTimestamp),
	};
}

/** Insert candle records into the market_candles table. */
export const insertCandles = async (data: CandleData[]): Promise<void> => {
	if (!data.length) {
		return;
	}

	await new DBConnection()
		.insertInto(T_MARKET_CANDLES)
		.values(data.map(_toCandleRow))
		.executeInsert();
};

/** Query helpers for the market_candles table, indexed by symbol, timestamp, and source. */
export const selectCandlesBy = {
	symbol: async (symbol: string) => {
		return await new DBConnection()
			.selectFrom(T_MARKET_CANDLES)
			.where(T_MARKET_CANDLES.symbol.equals(symbol))
			.select(SELECT)
			.executeSelectMany();
	},
	timestamp: {
		after: async (timestamp: Date) => {
			return await new DBConnection()
				.selectFrom(T_MARKET_CANDLES)
				.where(T_MARKET_CANDLES.timestamp.greaterThan(timestamp))
				.select(SELECT)
				.executeSelectMany();
		},
		before: async (timestamp: Date) => {
			return await new DBConnection()
				.selectFrom(T_MARKET_CANDLES)
				.where(T_MARKET_CANDLES.timestamp.lessThan(timestamp))
				.select(SELECT)
				.executeSelectMany();
		},
	},
	source: async (source: string) => {
		return await new DBConnection()
			.selectFrom(T_MARKET_CANDLES)
			.where(T_MARKET_CANDLES.source.equals(source))
			.select(SELECT)
			.executeSelectMany();
	},
};

// CREATE TABLE IF NOT EXISTS `market_candles` (
//   `id`               INT NOT NULL AUTO_INCREMENT,
//   `symbol`           VARCHAR(32) NOT NULL,
//   `market`           VARCHAR(16) NOT NULL,
//   `source`           VARCHAR(32) NOT NULL,
//   `interval_value`   VARCHAR(16) NOT NULL,
//   `open`             DECIMAL(20,10) NOT NULL,
//   `high`             DECIMAL(20,10) NOT NULL,
//   `low`              DECIMAL(20,10) NOT NULL,
//   `close`            DECIMAL(20,10) NOT NULL,
//   `volume`           DECIMAL(30,10) NOT NULL,
//   `trades`           INT NULL,
//   `timestamp`        DATETIME(3) NOT NULL,
//   `close_timestamp`  DATETIME(3) NOT NULL,

//   PRIMARY KEY (`id`, `symbol`, `market`, `interval_value`, `timestamp`, `source`),
//   INDEX `idx_candles_timestamp` (`timestamp` ASC) INVISIBLE,
//   INDEX `idx_candles_symbol` (`symbol` ASC) VISIBLE)
// ENGINE = InnoDB;
