import type {
	OrderBookLevel,
	SourceType,
} from "@trading-model/common/config/event.types";
import type {
	TradingSymbol,
	UnixTimestamp,
} from "@trading-model/common/domain/primitives";
import { Table } from "ts-sql-query/Table";

import { createDBConnection, type DBConnection } from "../../../config/db";
import type { OrderBookData } from "../market-data.types";

const T_ORDER_BOOK = new (class TOrderBook extends Table<
	DBConnection,
	"TOrderBook"
> {
	id = this.autogeneratedPrimaryKey("id", "int");
	symbol = this.primaryKey("symbol", "string");
	market = this.column("market", "string");
	source = this.column("source", "string");
	bids = this.column("bids", "string");
	asks = this.column("asks", "string");
	timestamp = this.primaryKey("timestamp", "localDateTime");

	constructor() {
		super("order_book_snapshots");
	}
})();

const SELECT = {
	symbol: T_ORDER_BOOK.symbol,
	market: T_ORDER_BOOK.market,
	source: T_ORDER_BOOK.source,
	bids: T_ORDER_BOOK.bids,
	asks: T_ORDER_BOOK.asks,
	timestamp: T_ORDER_BOOK.timestamp,
};

function serializeSet(entries: Set<OrderBookLevel>): string {
	return JSON.stringify(
		Array.from(entries).map((entry) => ({
			price: entry.price,
			quantity: entry.quantity,
		}))
	);
}

export const insertOrderBookSnapshot = async (
	data: OrderBookData[]
): Promise<void> => {
	if (!data.length) {
		return;
	}

	const rows = data.map((item) => ({
		symbol: item.symbol,
		market: item.market,
		source: item.source,
		bids: serializeSet(item.bids),
		asks: serializeSet(item.asks),
		timestamp: new Date(item.timestamp),
	}));

	await createDBConnection()
		.insertInto(T_ORDER_BOOK)
		.values(rows)
		.executeInsert();
};

export const selectOrderBookSnapshotsBy = {
	symbol: async (symbol: TradingSymbol) => {
		return await createDBConnection()
			.selectFrom(T_ORDER_BOOK)
			.where(T_ORDER_BOOK.symbol.equals(symbol))
			.select(SELECT)
			.executeSelectMany();
	},
	timestamp: {
		after: async (timestamp: UnixTimestamp) => {
			return await createDBConnection()
				.selectFrom(T_ORDER_BOOK)
				.where(T_ORDER_BOOK.timestamp.greaterOrEquals(new Date(timestamp)))
				.select(SELECT)
				.executeSelectMany();
		},
		before: async (timestamp: UnixTimestamp) => {
			return await createDBConnection()
				.selectFrom(T_ORDER_BOOK)
				.where(T_ORDER_BOOK.timestamp.lessOrEquals(new Date(timestamp)))
				.select(SELECT)
				.executeSelectMany();
		},
	},
	source: async (source: SourceType) => {
		return await createDBConnection()
			.selectFrom(T_ORDER_BOOK)
			.where(T_ORDER_BOOK.source.equals(source))
			.select(SELECT)
			.executeSelectMany();
	},
};
