import { Table } from 'ts-sql-query/Table';

import { DBConnection } from '../../../config/db';
import { OrderBookData } from '../market-data.types';

interface OrderBookSnapshotRow {
  symbol: string;
  market: string;
  source: string;
  bids: string;
  asks: string;
  timestamp: Date;
}

const tOrderBook = new (class TOrderBook extends Table<DBConnection, 'TOrderBook'> {
  id = this.autogeneratedPrimaryKey('id', 'int');
  symbol = this.primaryKey('symbol', 'string');
  market = this.column('market', 'string');
  source = this.column('source', 'string');
  bids = this.column('bids', 'string');
  asks = this.column('asks', 'string');
  timestamp = this.primaryKey('timestamp', 'localDateTime');

  constructor() {
    super('order_book_snapshots');
  }
})();

const select = {
  symbol: tOrderBook.symbol,
  market: tOrderBook.market,
  source: tOrderBook.source,
  bids: tOrderBook.bids,
  asks: tOrderBook.asks,
  timestamp: tOrderBook.timestamp,
};

function serializeSet(entries: Set<{ price: number; quantity: number }>): string {
  return JSON.stringify(Array.from(entries).map(e => [e.price, e.quantity]));
}

export const insertOrderBookSnapshot = async (data: OrderBookData[]): Promise<void> => {
  if (!data.length) return;

  const rows: OrderBookSnapshotRow[] = data.map(d => ({
    symbol: d.symbol,
    market: d.market,
    source: d.source,
    bids: serializeSet(d.bids),
    asks: serializeSet(d.asks),
    timestamp: new Date(d.timestamp),
  }));

  await new DBConnection()
    .insertInto(tOrderBook)
    .values(rows)
    .executeInsert();
};

export const selectOrderBookSnapshotsBy = {
  symbol: async (symbol: string) => {
    return await new DBConnection()
      .selectFrom(tOrderBook)
      .where(tOrderBook.symbol.equals(symbol))
      .select(select)
      .executeSelectMany();
  },
  timestamp: {
    after: async (timestamp: Date) => {
      return await new DBConnection()
        .selectFrom(tOrderBook)
        .where(tOrderBook.timestamp.greaterOrEquals(timestamp))
        .select(select)
        .executeSelectMany();
    },
    before: async (timestamp: Date) => {
      return await new DBConnection()
        .selectFrom(tOrderBook)
        .where(tOrderBook.timestamp.lessOrEquals(timestamp))
        .select(select)
        .executeSelectMany();
    },
  },
  source: async (source: string) => {
    return await new DBConnection()
      .selectFrom(tOrderBook)
      .where(tOrderBook.source.equals(source))
      .select(select)
      .executeSelectMany();
  },
};

// CREATE TABLE `order_book_snapshots` (
//     `id`          INT NOT NULL AUTO_INCREMENT,
//     `symbol`      VARCHAR(32) NOT NULL,
//     `market`      VARCHAR(16) NOT NULL,
//     `source`      VARCHAR(32) NOT NULL,
//     `bids`        JSON NOT NULL,
//     `asks`        JSON NOT NULL,
//     `timestamp`   DATETIME(3) NOT NULL,
//
//     PRIMARY KEY (`symbol`, `timestamp`),
//     INDEX `idx_obs_timestamp` (`timestamp` ASC) INVISIBLE,
//     INDEX `idx_obs_symbol` (`symbol` ASC) VISIBLE)
// ) ENGINE=InnoDB;
