import type { SourceType } from "@trading-model/common/config/event.types";
import type {
	TradingSymbol,
	UnixTimestamp,
} from "@trading-model/common/domain/primitives";
import { Table } from "ts-sql-query/Table";

import { createDBConnection, type DBConnection } from "../../../config/db";
import type { TickerData } from "../market-data.types";

const T_MARKET_TICKER = new (class TMarketTicker extends Table<
	DBConnection,
	"TMarketTicker"
> {
	id = this.autogeneratedPrimaryKey("id", "int");

	symbol = this.primaryKey("symbol", "string");
	market = this.primaryKey("market", "string");
	source = this.primaryKey("source", "string");

	low = this.column("low", "double");
	open = this.column("open", "double");
	high = this.column("high", "double");
	last = this.column("last", "double");
	volume = this.column("volume", "double");

	timestamp = this.primaryKey("timestamp", "localDateTime");
	closeTimestamp = this.primaryKey("close_time", "localDateTime");

	constructor() {
		super("market_tickers");
	}
})();

const SELECT = {
	low: T_MARKET_TICKER.low,
	open: T_MARKET_TICKER.open,
	high: T_MARKET_TICKER.high,
	last: T_MARKET_TICKER.last,
	symbol: T_MARKET_TICKER.symbol,
	market: T_MARKET_TICKER.market,
	source: T_MARKET_TICKER.source,
	volume: T_MARKET_TICKER.volume,
	timestamp: T_MARKET_TICKER.timestamp,
	closeTimestamp: T_MARKET_TICKER.closeTimestamp,
};

function _toTickerRow(item: TickerData): Record<string, unknown> {
	return {
		low: item.low,
		high: item.high,
		last: item.last,
		open: item.open,
		market: item.market,
		source: item.source,
		symbol: item.symbol,
		volume: item.volume,
		timestamp: new Date(item.timestamp),
		closeTimestamp: new Date(item.closeTimestamp),
	};
}

/** Insert 24-hour ticker records into the market_tickers table. */
export const insertTicker = async (data: TickerData[]): Promise<void> => {
	if (!data.length) {
		return;
	}

	await createDBConnection()
		.insertInto(T_MARKET_TICKER)
		.values(data.map(_toTickerRow))
		.executeInsert();
};

/** Query helpers for the market_tickers table, indexed by symbol, timestamp, and source. */
export const selectTickerBy = {
	symbol: async (symbol: TradingSymbol) => {
		return await createDBConnection()
			.selectFrom(T_MARKET_TICKER)
			.where(T_MARKET_TICKER.symbol.equals(symbol))
			.select(SELECT)
			.executeSelectMany();
	},
	timestamp: async (timestamp: UnixTimestamp) => {
		return await createDBConnection()
			.selectFrom(T_MARKET_TICKER)
			.where(T_MARKET_TICKER.timestamp.equals(new Date(timestamp)))
			.select(SELECT)
			.executeSelectMany();
	},
	source: async (source: SourceType) => {
		return await createDBConnection()
			.selectFrom(T_MARKET_TICKER)
			.where(T_MARKET_TICKER.source.equals(source))
			.select(SELECT)
			.executeSelectMany();
	},
};
