import type { SourceType } from "@trading-model/common/config/event.types";
import type { TradingSymbol, UnixTimestamp } from "@trading-model/common/domain/primitives";
import { Table } from "ts-sql-query/Table";

import { DBConnection } from "../../../config/db";
import type { TradeData } from "../market-data.types";

const T_MARKET_TRADES = new (class TMarketTrades extends Table<
	DBConnection,
	"TMarketTrades"
> {
	id = this.autogeneratedPrimaryKey("id", "int");

	symbol = this.primaryKey("symbol", "string");
	market = this.primaryKey("market", "string");
	source = this.primaryKey("source", "string");

	side = this.column("side", "string");
	price = this.column("price", "double");
	quantity = this.column("quantity", "double");
	tradeId = this.primaryKey("trade_id", "bigint");

	timestamp = this.primaryKey("timestamp", "localDateTime");

	constructor() {
		super("market_trades");
	}
})();

const SELECT = {
	side: T_MARKET_TRADES.side,
	price: T_MARKET_TRADES.price,
	symbol: T_MARKET_TRADES.symbol,
	market: T_MARKET_TRADES.market,
	source: T_MARKET_TRADES.source,
	tradeId: T_MARKET_TRADES.tradeId,
	quantity: T_MARKET_TRADES.quantity,
	timestamp: T_MARKET_TRADES.timestamp,
};

function _toTradeRow(item: TradeData): Record<string, unknown> {
	return {
		side: item.side,
		price: item.price,
		market: item.market,
		source: item.source,
		symbol: item.symbol,
		tradeId: item.tradeId,
		quantity: item.quantity,
		timestamp: new Date(item.timestamp),
	};
}

/** Insert trade records into the market_trades table. */
export const insertTrades = async (data: TradeData[]): Promise<void> => {
	if (!data.length) {
		return;
	}

	await new DBConnection()
		.insertInto(T_MARKET_TRADES)
		.values(data.map(_toTradeRow))
		.executeInsert();
};

/** Query helpers for the market_trades table, indexed by symbol, timestamp, and source. */
export const selectTradesBy = {
	symbol: async (symbol: TradingSymbol) => {
		return await new DBConnection()
			.selectFrom(T_MARKET_TRADES)
			.where(T_MARKET_TRADES.symbol.equals(symbol))
			.select(SELECT)
			.executeSelectMany();
	},
	timestamp: async (timestamp: UnixTimestamp) => {
		return await new DBConnection()
			.selectFrom(T_MARKET_TRADES)
			.where(T_MARKET_TRADES.timestamp.equals(new Date(timestamp)))
			.select(SELECT)
			.executeSelectMany();
	},
	source: async (source: SourceType) => {
		return await new DBConnection()
			.selectFrom(T_MARKET_TRADES)
			.where(T_MARKET_TRADES.source.equals(source))
			.select(SELECT)
			.executeSelectMany();
	},
};

// CREATE TABLE `market_trades` (
//     `id`          INT NOT NULL AUTO_INCREMENT,
//     `symbol`      VARCHAR(32) NOT NULL,
//     `market`      VARCHAR(16) NOT NULL,
//     `source`      VARCHAR(32) NOT NULL,
//     `trade_id`    BIGINT NOT NULL,
//     `price`       DECIMAL(20,10) NOT NULL,
//     `quantity`    DECIMAL(30,10) NOT NULL,
//     `side`        ENUM('buy', 'sell') NOT NULL,
//     `timestamp`   DATETIME(3) NOT NULL,
//
//     PRIMARY KEY (`symbol`, `market`, `source`, `trade_id`, `timestamp`),
//     INDEX `idx_trades_timestamp` (`timestamp` ASC) INVISIBLE,
//     INDEX `idx_trades_symbol` (`symbol` ASC) VISIBLE)
// ) ENGINE=InnoDB;
