import { Table } from "ts-sql-query/Table";
import { DBConnection } from "../config/db";

class ChartTableDefinition extends Table<DBConnection, "tChartCandle"> {
  id = this.autogeneratedPrimaryKey("id", "int");
  symbol = this.column("symbol", "string"); // ex: BTCUSDT
  interval = this.column("interval", "string"); // ex: '1m', '5m', '1h'
  open = this.column("open", "double");
  high = this.column("high", "double");
  low = this.column("low", "double");
  close = this.column("close", "double");
  volume = this.column("volume", "double");
  openTime = this.column("open_time", "localDateTime");
  closeTime = this.column("close_time", "localDateTime");
  quoteAssetVolume = this.optionalColumn("quote_asset_volume", "double");
  numberOfTrades = this.optionalColumn("number_of_trades", "int");
  takerBuyBaseAssetVolume = this.optionalColumn("taker_buy_base_asset_volume", "double");
  takerBuyQuoteAssetVolume = this.optionalColumn("taker_buy_quote_asset_volume", "double");
  source = this.optionalColumn("source", "string"); // ex: 'binance', 'yahoo'

  constructor() {
    super("chart_candle");
  }
};

export const tChartCandle = new ChartTableDefinition()

export type ChartCandleType = {
  id: number;
  symbol: string;
  interval: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  openTime: Date;
  closeTime: Date;
  source?: string;
};

export const selectChartColumns = {
  id: tChartCandle.id,
  symbol: tChartCandle.symbol,
  interval: tChartCandle.interval,
  open: tChartCandle.open,
  high: tChartCandle.high,
  low: tChartCandle.low,
  close: tChartCandle.close,
  volume: tChartCandle.volume,
  openTime: tChartCandle.openTime,
  closeTime: tChartCandle.closeTime,
  source: tChartCandle.source,
};