import { Table } from "ts-sql-query/Table";
import { DBConnection } from "../config/db";

class ChartTableDefinition extends Table<DBConnection, "tChartCandle"> {
  id = this.autogeneratedPrimaryKey("id", "int");
  symbol = this.column("symbol", "string"); // ex: BTCUSDT
  interval = this.column("interval", "string"); // ex: '1m', '5m', '1h'
  open = this.column("open", "double");
  high = this.column("high", "double");
  low = this.column("low", "double");
  close = this.column("close", "double");
  volume = this.column("volume", "double");
  timestamp = this.column("timestamp", "localDateTime");
  source = this.optionalColumn("source", "string"); // ex: 'binance', 'yahoo'

  constructor() {
    super("chart_candle");
  }
};

export const tChartCandle = new ChartTableDefinition()

export type ChartCandleType = {
  id: number;
  symbol: string;
  interval: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  timestamp: Date;
  source?: string;
};

export const selectColumns = {
  id: tChartCandle.id,
  symbol: tChartCandle.symbol,
  interval: tChartCandle.interval,
  open: tChartCandle.open,
  high: tChartCandle.high,
  low: tChartCandle.low,
  close: tChartCandle.close,
  volume: tChartCandle.volume,
  timestamp: tChartCandle.timestamp,
  source: tChartCandle.source,
};