import { DBConnection } from "config/db";
import { Table } from "ts-sql-query/Table";
// import { Column } from "your-db-types"; // adapte si besoin

class TradeTableDefinition extends Table<DBConnection, "tTrade"> {
  id = this.autogeneratedPrimaryKey("id", "int");
  exchangeId = this.column("exchange_id", "int");
  symbol = this.column("symbol", "string"); 
  price = this.column("price", "int");
  qty = this.column("qty", "int");
  time = this.column("time", "localDateTime");
  isBuyerMaker = this.column("is_buyer_maker", "boolean");
  isBestMatch = this.column("is_best_match", "boolean");
  source = this.optionalColumn("source", "string");
  quoteQty = this.optionalColumn("quote_qty", "int");
  createdAt = this.optionalColumn("created_at", "localDateTime");

  constructor () {
    super("trade");
  }
};

export const tTrade = new TradeTableDefinition();

export type TradeType = {
 id: number;
 exchangeId: number;
 symbol: string;
 price: number;
 qty: number;
 time: Date;
 isBuyerMaker: boolean;
 isBestMatch: boolean;
 source?: string;
 quoteQty?: number;
 createdAt?: Date;
}

export const selectTradesColumns = {
  id: tTrade.id,
  exchangeId: tTrade.exchangeId,
  symbol: tTrade.symbol,
  price: tTrade.price,
  qty: tTrade.qty,
  time: tTrade.time,
  isBuyerMaker: tTrade.isBuyerMaker,
  isBestMatch: tTrade.isBestMatch,
  source: tTrade.source,
  quoteQty: tTrade.quoteQty,
  createdAt: tTrade.createdAt,
};