import { Table } from "ts-sql-query/Table";
import { DBConnection } from "../../../config/db";
import { CandleEntity } from "../market-data.types";

const tMarketCandles = new class TMarketCandles extends Table<DBConnection, 'TMarketCandles'> {
    id = this.autogeneratedPrimaryKey('id', 'int');

    symbol = this.primaryKey('symbol', 'string');
    market = this.primaryKey('market', 'string');
    source = this.primaryKey('source', 'string');
    interval = this.primaryKey('interval_value', 'string');

    low = this.column('low', 'double');
    open = this.column('open', 'double');
    high = this.column('high', 'double');
    close = this.column('close', 'double');
    volume = this.column('volume', 'double');
    trades = this.optionalColumn('trades', 'int');

    closeTimestamp = this.column("close_timestamp", "localDateTime");
    timestamp = this.primaryKey('timestamp', 'localDateTime');

    constructor() {
        super('market_candles');
    }
}();

const select = {
    low: tMarketCandles.low,
    open: tMarketCandles.open,
    high: tMarketCandles.high,
    close: tMarketCandles.close,
    symbol: tMarketCandles.symbol,
    market: tMarketCandles.market,
    source: tMarketCandles.source,
    volume: tMarketCandles.volume,
    interval: tMarketCandles.interval,
    trades: tMarketCandles.trades,
    timestamp: tMarketCandles.timestamp,
    closeTimestamp: tMarketCandles.closeTimestamp,
}

export const insertCandles = async (data: CandleEntity[]): Promise<void> => {
    if (!data.length) return;

    await new DBConnection()
    .insertInto(tMarketCandles)
    .values(
        data.map((d) => ({
            low: d.low,
            open: d.open,
            high: d.high,
            close: d.close,
            symbol: d.symbol,
            market: d.market,
            source: d.source,
            volume: d.volume,
            interval: d.interval,
            trades: d.trades ?? null,
            timestamp: new Date(d.timestamp),
            closeTimestamp: new Date(d.closeTimestamp)
        }))
    )
    .executeInsert();
}

export const selectCandlesBy = {
    symbol: async (symbol: string) => {
        return await new DBConnection()
        .selectFrom(tMarketCandles)
        .where(tMarketCandles.symbol.equals(symbol))
        .select(select)
        .executeSelectMany();
    },
    timestamp: async (timestamp: Date) => {
        return await new DBConnection()
        .selectFrom(tMarketCandles)
        .where(tMarketCandles.timestamp.equals(timestamp))
        .select(select)
        .executeSelectMany();
    },
    source: async (source: string) => {
        return await new DBConnection()
        .selectFrom(tMarketCandles)
        .where(tMarketCandles.source.equals(source))
        .select(select)
        .executeSelectMany();
    }
}

// CREATE TABLE IF NOT EXISTS `market_candles` (
//   `id`               INT NOT NULL AUTO_INCREMENT,
//   `symbol`           VARCHAR(32) NOT NULL,
//   `market`           VARCHAR(16) NOT NULL,
//   `source`           VARCHAR(32) NOT NULL,
//   `interval_value`   VARCHAR(16) NOT NULL,
//   `open`             DECIMAL(20,10) NOT NULL,
//   `high`             DECIMAL(20,10) NOT NULL,
//   `low`              DECIMAL(20,10) NOT NULL,
//   `close`            DECIMAL(20,10) NOT NULL,
//   `volume`           DECIMAL(30,10) NOT NULL,
//   `trades`           INT NULL,
//   `timestamp`        DATETIME(3) NOT NULL,
//   `close_timestamp`  DATETIME(3) NOT NULL,

//   PRIMARY KEY (`id`, `symbol`, `market`, `interval_value`, `timestamp`, `source`),
//   INDEX `idx_candles_timestamp` (`timestamp` ASC) INVISIBLE,
//   INDEX `idx_candles_symbol` (`symbol` ASC) VISIBLE)
// ENGINE = InnoDB;