import { Table } from "ts-sql-query/Table";
import { DBConnection } from "../../../config/db";
import { TickerEntity } from "../market-data.types";

const tMarketTicker = new class TMarketTicker extends Table<DBConnection, 'TMarketTicker'> {
    id = this.autogeneratedPrimaryKey('id', 'int');

    symbol = this.primaryKey('symbol', 'string');
    market = this.primaryKey('market', 'string');
    source = this.primaryKey('source', 'string');

    low = this.column('low', 'double');
    open = this.column('open', 'double');
    high = this.column('high', 'double');
    last = this.column('last', 'double');
    volume = this.column('volume', 'double');

    timestamp = this.primaryKey('timestamp', 'localDateTime');
    closeTimestamp = this.primaryKey('close_time', 'localDateTime');

    constructor() {
        super('market_tickers');
    }
}();

const select = {
    low: tMarketTicker.low,
    open: tMarketTicker.open,
    high: tMarketTicker.high,
    last: tMarketTicker.last,
    symbol: tMarketTicker.symbol,
    market: tMarketTicker.market,
    source: tMarketTicker.source,
    volume: tMarketTicker.volume,
    timestamp: tMarketTicker.timestamp,
    closeTimestamp: tMarketTicker.closeTimestamp,
}

export const insertTicker = async (data: TickerEntity[]): Promise<void> => {
    if (!data.length) return;

    await new DBConnection()
    .insertInto(tMarketTicker)
    .values(data.map(d => ({
        low: d.low,
        high: d.high,
        last: d.last,
        open: d.open,
        market: d.market,
        source: d.source,
        symbol: d.symbol,
        volume: d.volume,
        timestamp: new Date(d.timestamp),
        closeTimestamp: new Date(d.closeTimestamp),
    })))
    .executeInsert();
}

export const selectTickerBy = {
    symbol: async (symbol: string) => {
        return await new DBConnection()
        .selectFrom(tMarketTicker)
        .where(tMarketTicker.symbol.equals(symbol))
        .select(select)
        .executeSelectMany();
    },
    timestamp: async (timestamp: Date) => {
        return await new DBConnection()
        .selectFrom(tMarketTicker)
        .where(tMarketTicker.timestamp.equals(timestamp))
        .select(select)
        .executeSelectMany();
    },
    source: async (source: string) => {
        return await new DBConnection()
        .selectFrom(tMarketTicker)
        .where(tMarketTicker.source.equals(source))
        .select(select)
        .executeSelectMany();
    }
}

// CREATE TABLE IF NOT EXISTS `market_tickers` (
//   `id`               INT NOT NULL AUTO_INCREMENT,
//   `symbol`           VARCHAR(32) NOT NULL,
//   `market`           VARCHAR(16) NOT NULL,
//   `source`           VARCHAR(32) NOT NULL,
//   `open`             DECIMAL(20,10) NOT NULL,
//   `high`             DECIMAL(20,10) NOT NULL,
//   `low`              DECIMAL(20,10) NOT NULL,
//   `last`             DECIMAL(20,10) NOT NULL,
//   `volume`           DECIMAL(30,10) NOT NULL,
//   `timestamp`        DATETIME(3) NOT NULL,
//   `close_time`        DATETIME(3) NOT NULL,

//   PRIMARY KEY (`id`, `symbol`, `market`, `timestamp`, `source`),
//   INDEX `idx_tickers_timestamp` (`timestamp` ASC) INVISIBLE,
//   INDEX `idx_tickers_symbol` (`symbol` ASC) VISIBLE)
// ENGINE = InnoDB;