import { Table } from "ts-sql-query/Table";
import { DBConnection } from "../../../config/db";
import { TradeEntity } from "../market-data.types";

const tMarketTrades = new class TMarketTrades extends Table<DBConnection, 'TMarketTrades'> {
    id = this.autogeneratedPrimaryKey('id', 'int');

    symbol = this.primaryKey('symbol', 'string');
    market = this.primaryKey('market', 'string');
    source = this.primaryKey('source', 'string');

    side = this.column('side', 'string');
    price = this.column('price', 'double');
    quantity = this.column('quantity', 'double');
    tradeId = this.primaryKey('trade_id', 'bigint');

    timestamp = this.primaryKey('timestamp', 'localDateTime');

    constructor() {
        super('market_trades');
    }
}();

const select = {
    side: tMarketTrades.side,
    price: tMarketTrades.price,
    symbol: tMarketTrades.symbol,
    market: tMarketTrades.market,
    source: tMarketTrades.source,
    tradeId: tMarketTrades.tradeId,
    quantity: tMarketTrades.quantity,
    timestamp: tMarketTrades.timestamp,
}

export const insertTrades = async (data: TradeEntity[]): Promise<void> => {
    if (!data.length) return;

    await new DBConnection()
    .insertInto(tMarketTrades)
    .values(
        data.map((d) => ({
            side: d.side,
            price: d.price,
            market: d.market,
            source: d.source,
            symbol: d.symbol,
            tradeId: d.tradeId,
            quantity: d.quantity,
            timestamp: new Date(d.timestamp),
        }))
    )
    .executeInsert();
}


export const selectTradesBy = {
    symbol: async (symbol: string) => {
        return await new DBConnection()
        .selectFrom(tMarketTrades)
        .where(tMarketTrades.symbol.equals(symbol))
        .select(select)
        .executeSelectMany();
    },
    timestamp: async (timestamp: Date) => {
        return await new DBConnection()
        .selectFrom(tMarketTrades)
        .where(tMarketTrades.timestamp.equals(timestamp))
        .select(select)
        .executeSelectMany();
    },
    source: async (source: string) => {
        return await new DBConnection()
        .selectFrom(tMarketTrades)
        .where(tMarketTrades.source.equals(source))
        .select(select)
        .executeSelectMany();
    }
}

// CREATE TABLE `market_trades` (
//     `id`          INT NOT NULL AUTO_INCREMENT,
//     `symbol`      VARCHAR(32) NOT NULL,
//     `market`      VARCHAR(16) NOT NULL,
//     `source`      VARCHAR(32) NOT NULL,
//     `trade_id`    BIGINT NOT NULL,
//     `price`       DECIMAL(20,10) NOT NULL,
//     `quantity`    DECIMAL(30,10) NOT NULL,
//     `side`        ENUM('buy', 'sell') NOT NULL,
//     `timestamp`   DATETIME(3) NOT NULL,

//     PRIMARY KEY (`symbol`, `market`, `source`, `trade_id`, `timestamp`),
//     INDEX `idx_trades_timestamp` (`timestamp` ASC) INVISIBLE,
//     INDEX `idx_trades_symbol` (`symbol` ASC) VISIBLE)
// ) ENGINE=InnoDB;