export const HTTP_HEADERS = {
	X_FORWARDED_FOR: "x-forwarded-for",
	X_FORWARDED_PROTO: "x-forwarded-proto",
	X_REQUEST_ID: "x-request-id",
	X_API_KEY: "x-api-key",
	CORRELATION_ID: "x-correlation-id",
	X_INSTANCE_TOKEN: "x-instance-token",
	X_INSTANCE_ID: "x-instance-id",
	X_SERVICE_NAME: "x-service-name",
	X_SUBSCRIBED_TOPICS: "x-subscribed-topics",
	X_TIMESTAMP: "x-timestamp",
	X_SIGNATURE: "x-signature",
	X_VAULT_NAMESPACE: "X-Vault-Namespace",
	CONTENT_TYPE: "Content-Type",
} as const;
