export type HttpStatusCode = number & { readonly brand: "HttpStatusCode" };

export const HTTP_STATUS = {
	OK: 200 as HttpStatusCode,
	CREATED: 201 as HttpStatusCode,
	ACCEPTED: 202 as HttpStatusCode,
	NO_CONTENT: 204 as HttpStatusCode,
	MOVED_PERMANENTLY: 301 as HttpStatusCode,
	FOUND: 302 as HttpStatusCode,
	NOT_MODIFIED: 304 as HttpStatusCode,
	GONE: 410 as HttpStatusCode,
	PAYMENT_REQUIRED: 402 as HttpStatusCode,
	IM_A_TEAPOT: 418 as HttpStatusCode,
	PAYLOAD_TOO_LARGE: 413 as HttpStatusCode,
	INVALID_TOKEN: 498 as HttpStatusCode,
	BAD_REQUEST: 400 as HttpStatusCode,
	UNAUTHORIZED: 401 as HttpStatusCode,
	FORBIDDEN: 403 as HttpStatusCode,
	REQUEST_TIMEOUT: 408 as HttpStatusCode,
	NOT_FOUND: 404 as HttpStatusCode,
	METHOD_NOT_ALLOWED: 405 as HttpStatusCode,
	CONFLICT: 409 as HttpStatusCode,
	UNSUPPORTED_MEDIA_TYPE: 415 as HttpStatusCode,
	UNPROCESSABLE_ENTITY: 422 as HttpStatusCode,
	TOO_MANY_REQUESTS: 429 as HttpStatusCode,
	INTERNAL_SERVER_ERROR: 500 as HttpStatusCode,
	BAD_GATEWAY: 502 as HttpStatusCode,
	SERVICE_UNAVAILABLE: 503 as HttpStatusCode,
	GATEWAY_TIMEOUT: 504 as HttpStatusCode,
} as const;
