export enum EncodingIndex {
	Gamma = 0,
	LearningRate = 1,
	ClipMin = 2,
	ClipMax = 3,
	ScaleFactor = 4,
	MaxEpisodeLength = 5,
	NStepReturn = 6,
	FrameSkip = 7,
	EpsilonStart = 8,
	EpsilonMin = 9,
	EpsilonDecay = 10,
	Temperature = 11,
	NoiseStd = 12,
	NoiseDecay = 13,
	BufferSize = 14,
	AlphaPER = 15,
	BetaPER = 16,
	MutationRate = 17,
	MutationSigma = 18,
	MutationSelfSigma = 19,
	NetworkInputDim = 20,
	NetworkOutputDim = 21,
	NetworkDepth = 22,
}

export const SCALAR_DIM = 23;
